[build]
  # 빌드 명령어 (정적 HTML이므로 빌드 불필요)
  command = "echo 'Static site deployment'"
  
  # 배포할 디렉토리 (루트 디렉토리)
  publish = "."
  
  # 기본 인덱스 파일 명시
  [build.processing]
    skip_processing = true

[build.environment]
  # Node.js 버전 지정
  NODE_VERSION = "18"

# 리다이렉트 설정 (SPA 대응)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 캐시 설정
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"